### ISSUE TITLE
What should I do when I need something from someone else to work on my PR?

### ISSUE THREAD

**Issue by idelahoz** [coderly/process#35]
# the problem.

When developing a large feature, that's made by several tasks, sometimes the code for each task is so coupled that it makes sense to keep everything into a single PR.

The main issue with this is task labeling, if I mark a task as "awaiting review", someone clicks on the PR link, and the PR is at "needs work"(cause its not fully done yet), its inconsistent.

How should we deal with this case?
### Person working on PR

**What should I do when I need something from someone else so I can work most effectively on my PR?**
### Person helping out
- What tasks need my attention
- What do you need from me for each task?
- How important is each thing you need from me? (Helps me prioritize when I don't have much time)
### PM (Josh or Venkat)
- Is every task on track to be completed for this sprint?
- Are there any tasks that are at risk to not be completed for this sprint?

**Comment by venkatd** [comment]
I think `needs work` has too many meanings. It should mean "someone wanted a code review before merge but it was reviewed and actually there are some changes that should be made"

**Comment by joshsmith** [comment]
I actually have a proposal for this.

If you have a large PR that has multiple tasks related to it, and you want the specific piece that you worked on to be reviewed, I think you should:
- Add a comment to the PR summarizing what you did
- Link to that comment in the Asana task you're going to mark as `awaiting review`
- Now when you click that link, you don't really care what the label of the PR itself is. It could be `blocked` for all you care, but you now have a place to review and comment on the task at hand.

What do you think @idelahoz and @venkatd?

**Comment by idelahoz** [comment]
I agree, I'll do that with my task, what I did in the meantime was creating a checklist on the PR description, but what you say makes sense.

**Comment by idelahoz** [comment]
what do you think @venkatd ?

**Comment by venkatd** [comment]
I was thinking we could do something like when we have questions:

https://github.com/coderly/process/issues/31

@begedin and I were doing this with Storypad and it seemed to work pretty well. Also it shows up in the GitHub UI so you know what needs to get resolved for the PR to get closed.

**Comment by venkatd** [comment]
@JoshSmith what do you think of creating GH issues whenever someone has a question or needs feedback on a PR? The reasons are
- The code related discussion is kept in GH so the integration is done automatically for us
- When reviewing a PR, our job is to make sure the related issues get resolved--which we can see in the PR itself as we are reviewing it.

You can see an example of this in action:
https://github.com/coderly/reissued-ember/pull/295

We may need more visibility on the outstanding issues that need to get resolved but I think this is a good starting point.

**Comment by venkatd** [comment]
I am looking at this as two JTBD "jobs"

What tasks others working on need my attention? This could be in the form of code reviews, questions, general feedback.

Then once we are looking at a specific task that needs your attention (say **Edit products** for example)

What exactly is needed from me for the **Edit products** task so that you have everything you need to keep forging ahead? (Do you need a code review? Do you have unresolved questions?)

**Comment by idelahoz** [comment]
@venkatd the thing would be how to reflect this in asana, which is where the client sees our progress, some task may be awaiting review there, so when you click the link on the task, where should the link take you?

**Comment by venkatd** [comment]
So based on the requirements above, I think we need something in Asana that indicates that either the task is completely blocked or needs attention from someone else. Both really mean the same thing except blocked is much more important than needs attention (or whatever we want to call that).

I think we don't need more granularity than this because the workflow is basically to go through all of the things that need my attention and address each one.

Then with an individual task, let me list out all the possibilities I can think of where you are working on a PR and you need something:
- I want a code review of what I have so far. I'm not done yet but this will reduce the risk of me going down the wrong path.
- I want a code review but I don't want to move ahead because there is a major fork in the road. For example, how to handle image uploads.
- I have some questions related to this. I can't move forward until they are answered.
- I have some questions from this. I'm not blocked right away but want them answered.

**I think we should keep in mind that the goal of all the labels and everything is that the following 3 things are addressed in the Asana/GH system**
- What tasks need my attention
- What do you need from me for each task?
- How important is each thing you need from me? (Helps me prioritize when I don't have much time)

So based on the above things, I think we can design the labels.

**Comment by venkatd** [comment]
Then the need of the person working on the PR is

**What should I do when I need something from someone else so I can work most effectively on my PR?**

**Comment by joshsmith** [comment]
> I want a code review of what I have so far. I'm not done yet but this will reduce the risk of me going down the wrong path.

`awaiting review` `needs attention`

> I want a code review but I don't want to move ahead because there is a major fork in the road. For example, how to handle image uploads.

`awaiting review` `blocked`

> I have some questions related to this. I can't move forward until they are answered.

`question` `blocked`

> I have some questions from this. I'm not blocked right away but want them answered.

`question` `needs attention`

**Comment by venkatd** [comment]
So to understand you are saying `needs attention` and `blocked` are the priorities.

And `question` and `awaiting review` are what is needed.

Any ideas on how we can simplify this so that it is easier to remember?

**Comment by joshsmith** [comment]
I don't think there's much simplification needed here, and we shouldn't need to remember if we start using the process guide. If we're _not_ referring to that first, especially with so many changes, then we're bound to make mistakes regardless.

**Comment by idelahoz** [comment]
the other option would be creating specific labels for the combinations, but I think that should be even harder to remember.

**Comment by venkatd** [comment]
I do think it's always a good exercise to try and simplify things. The `code start` and `code publish` IMHO reduce the friction for doing the right thing because of the time spent trying to make it simpler.

For example, I'm thinking we can get rid of the `needs attention` label because everything needs attention. Our workflow should be to go through every `question` and `awaiting review` label and put the ball back in the court of whoever is working on the PR.

If we focus out the workflow of the user then that will guide us in simplifying the processes

@idelahoz yeah I agree

**Comment by joshsmith** [comment]
Are you suggesting something more like?

> I want a code review of what I have so far. I'm not done yet but this will reduce the risk of me going down the wrong path.

`awaiting review`

> I want a code review but I don't want to move ahead because there is a major fork in the road. For example, how to handle image uploads.

`awaiting review` `blocked`

> I have some questions related to this. I can't move forward until they are answered.

`question` `blocked`

> I have some questions from this. I'm not blocked right away but want them answered.

`question`

**Comment by venkatd** [comment]
And I agree about following the process guide. Whatever we can do to make the right thing easier to do is a win in my opinion.

Yeah exactly what you had minus the `needs attention` label.

**Comment by joshsmith** [comment]
Wait, minus removing it?

**Comment by venkatd** [comment]
Edited :)

**Comment by joshsmith** [comment]
Okay so @idelahoz @begedin what do you think of https://github.com/coderly/process/issues/35#issuecomment-83630917

**Comment by begedin** [comment]
I agree with the comment in general, but "awaiting review blocked" and "question blocked" don't feel completely separate to me. Do we need both combinations? To me, it seems like the proper reaction to both cases is "take a look at the PR as is and try to answer any questions you can".

**Comment by venkatd** [comment]
We need to decide what the workflow of the reviewer needs to be. The distinctions are mainly a matter of prioritization.

If we see a question or blocked question we can take a few minutes and answer all the questions. If we need to review code then there is a lot more time we need to allocate for that. There is naturally a conflict here: your productivity vs. your teammates productivity.

_We want to maximize the team productivity not our individual productivity_.

My thoughts are as follows:
- Go through code that is `awaiting review` and review twice per day
- Go through `blocked` questions and PRs between breaks. The turnaround time should be 2 hours tops.
- Go through any `question` labels between breaks also. Turnaround here should be 3 hours.

I'm going to go ahead and create a PR so we at least have an improvement to our label system. From now on as we improve the labels, let us make sure to link to real examples. Discussing these things abstractly will lead us to suboptimal solutions.

### A side note

When we get blocked, we should also ask ourselves _why did this get blocked in the first place?_ ... most things that end up getting blocked are usually a symptom of miscommunication. In other words, when something becomes urgent, you have to ask: did this become urgent because I didn't plan ahead?
