### ISSUE TITLE
Regular upgrades of backend and front end

### ISSUE THREAD

**Issue by venkatd** [coderly/process#68]
I think we can all agree that the past week's upgrades were a huge nightmare. I think we need a regular upgrade process.
- How often should we be upgrading?
- How long should we wait before upgrading a library? I'm assuming we should generally not be guinea pigs for beta versions and are probably best waiting a week or so one a new version is released.
- Are there any tools that will alert us when it is a good idea to upgrade? Any rules of thumb we can use?

**Comment by begedin** [comment]
Regarding 'how often', I'm not sure it would've been a huge help here. It's usually easier when we don't skip versions, but in this case, looking at the changelog, 0.2.1 consisted mainly of fixes to 0.2.0.

I would agree with waiting a bit, because we need to make sure that the ember-cli addons we're using are also upgraded to the new version (if required).
